import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'edibles',
  title: 'Edibles',
  type: 'document',
  fields: [
    defineField({
      name: 'brand',
      title: 'Brand',
      type: 'string',
      description: 'What brand made these edibles?',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      description: 'The name of the product.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'string',
      description: 'Describe the product. Keep it short. Note, this field is optional.',
    }),
    defineField({
      name: 'image',
      title: 'Image',
      type: 'image',
      description: 'An image of the product.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'thcContent',
      title: 'THC Content',
      type: 'string',
      description: 'How much THC is in this product, total?',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'price',
      title: 'Price',
      type: 'string',
      description: 'Pricing information for your specific quantity.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'new',
      title: 'New',
      type: 'boolean',
      description: 'Would you like to advertise this strain as \'new\'?',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'ourPick',
      title: 'Our Pick',
      type: 'boolean',
      description: 'Would you like to advertise this strain as a Green Squirrel favorite?',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'almostGone',
      title: 'Leaving Rotation Soon?',
      type: 'boolean',
      description: 'Is this item almost out of stock, or leaving the current rotation soon?',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'smallGiftEligible',
      title: 'Small Gift Eligibility',
      type: 'boolean',
      description: 'Is this item eligible for redemption as a small gift?',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'mediumGiftEligible',
      title: 'Medium Gift Eligibility',
      type: 'boolean',
      description: 'Is this item eligible for redemption as a medium gift?',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'standardGiftEligible',
      title: 'Standard Gift Eligibility',
      type: 'boolean',
      description: 'Is this item eligible for redemption as a standard gift?',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'premiumGiftEligible',
      title: 'Premium Gift Eligibility',
      type: 'boolean',
      description: 'Is this item eligible for redemption as a premium gift?',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'squirrelReserveEligible',
      title: 'Squirrel Reserve Gift Eligibility',
      type: 'boolean',
      description: 'Is this item eligible for redemption as a squirrel reserve gift?',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'visible',
      title: 'Visibility',
      type: 'boolean',
      description: 'Do you want this item shown on the website? (You can edit this flag for seasonal items, out of stock inventory, etc...)',
      validation: (Rule) => Rule.required(),
    }),
  ],
});